const $=id=>document.getElementById(id);let state=null,pollTimer=null,localProgress=0,seeking=false,rateLimitedUntil=0,lastArtwork="",queue=Promise.resolve(),liked=false;let settings={rotationSeconds:8,compact:false,glow:true,mini:false,pinned:false,startup:false};const PLAYING=15000,PAUSED=30000,EMPTY=30000;
const fmt=(ms=0)=>{const s=Math.max(0,Math.floor(ms/1000));return `${Math.floor(s/60)}:${String(s%60).padStart(2,"0")}`};
function show(w){$("setup").classList.toggle("hidden",w!=="setup");$("player").classList.toggle("hidden",w!=="player")}
function setError(m="",rate=false){$("error").textContent=m;$("error").classList.toggle("rate-limit",rate)}
function setPlaying(on){$("app").classList.toggle("idle",!on);$("vinyl").classList.toggle("paused",!on);$("playBtn").textContent=on?"Ⅱ":"▶"}
function tone(r,on){$("tonearm").style.transform=on?`rotate(${-16+Math.max(0,Math.min(1,r))*9}deg)`:"rotate(-33deg)"}
function applySettings(){
  $("vinyl").style.animationDuration=`${settings.rotationSeconds}s`;
  $("glow").style.display=settings.glow?"":"none";
  $("app").classList.toggle("compact",settings.compact);
  $("app").classList.toggle("mini",settings.mini);
  $("rotationSpeed").value=settings.rotationSeconds;
  $("glowToggle").checked=settings.glow;
  $("compactToggle").checked=settings.compact;
  $("startupToggle").checked=settings.startup;
}
async function saveSettings(){settings={...settings,rotationSeconds:Number($("rotationSpeed").value),glow:$("glowToggle").checked,compact:$("compactToggle").checked};applySettings();await window.deez.setSettings(settings)}
function colors(img){try{const c=document.createElement("canvas");c.width=c.height=40;const x=c.getContext("2d",{willReadFrequently:true});x.drawImage(img,0,0,40,40);const d=x.getImageData(0,0,40,40).data,b=new Map();for(let i=0;i<d.length;i+=16){const a=[0,1,2].map(k=>Math.round(d[i+k]/32)*32),v=(a[0]+a[1]+a[2])/3;if(v<25||v>235)continue;const key=a.join(",");b.set(key,(b.get(key)||0)+1)}const cs=[...b].sort((a,z)=>z[1]-a[1]).slice(0,2).map(x=>`rgb(${x[0]})`);document.documentElement.style.setProperty("--c1",cs[0]||"#7c4dff");document.documentElement.style.setProperty("--c2",cs[1]||"#171027")}catch{}}
function marquee(){document.querySelectorAll(".marquee").forEach(box=>box.classList.toggle("active",box.firstElementChild.scrollWidth>box.clientWidth+8))}
async function loadLike(id){if(!id)return;try{liked=await window.deez.isSaved(id);$("likeBtn").textContent=liked?"♥":"♡";$("likeBtn").classList.toggle("on",liked)}catch{}}
function render(s){state=s;if(!s?.item){$("track").textContent="אין שיר פעיל";$("artist").textContent="פתח את Spotify או בחר מכשיר למטה";$("current").textContent=$("duration").textContent="0:00";$("progress").value=0;localProgress=0;tone(0,false);setPlaying(false);return}$("track").textContent=s.item.name||"Unknown";$("artist").textContent=(s.item.artists||[]).map(a=>a.name).join(", ")+(s.device?.name?` • ${s.device.name}`:"");setTimeout(marquee,30);const image=s.item.album?.images?.[0]?.url;if(image&&image!==lastArtwork){lastArtwork=image;$("vinyl").classList.add("changing");setTimeout(()=>{$("cover").crossOrigin="anonymous";$("cover").onload=()=>{colors($("cover"));$("vinyl").classList.remove("changing")};$("cover").src=image},250);loadLike(s.item.id)}localProgress=Math.min(s.progress_ms||0,s.item.duration_ms||0);$("duration").textContent=fmt(s.item.duration_ms);$("current").textContent=fmt(localProgress);const r=localProgress/Math.max(1,s.item.duration_ms);$("progress").value=Math.round(r*1000);tone(r,!!s.is_playing);$("volume").value=s.device?.volume_percent??50;$("volumeValue").textContent=`${$("volume").value}%`;setPlaying(!!s.is_playing);$("shuffleBtn").classList.toggle("on",!!s.shuffle_state);$("repeatBtn").classList.toggle("on",s.repeat_state!=="off");$("repeatOne").style.display=s.repeat_state==="track"?"block":"none"}
function rate(e){const m=String(e?.message||e||"").match(/RATE_LIMIT:(\d+)/);return m?Number(m[1]):0}function enterRate(sec){rateLimitedUntil=Date.now()+Math.max(1,sec)*1000;clearTimeout(pollTimer);updateRate();pollTimer=setTimeout(poll,sec*1000+300)}function updateRate(){if(Date.now()>=rateLimitedUntil){if($("error").classList.contains("rate-limit"))setError("");return}const l=Math.ceil((rateLimitedUntil-Date.now())/1000),h=Math.floor(l/3600),m=Math.floor((l%3600)/60),s=l%60;setError(`Spotify מגבילה זמנית בקשות. ניסיון בעוד ${h?`${h}:`:""}${String(m).padStart(2,"0")}:${String(s).padStart(2,"0")}`,true)}setInterval(updateRate,1000);
const delay=()=>!state?.item?EMPTY:state.is_playing?PLAYING:PAUSED;function schedule(ms=delay()){clearTimeout(pollTimer);pollTimer=setTimeout(poll,ms)}async function poll(){if(Date.now()<rateLimitedUntil)return schedule(rateLimitedUntil-Date.now()+300);try{render(await window.deez.getPlayer());setError("");schedule()}catch(e){const s=rate(e);if(s)return enterRate(s);if(String(e.message).includes("NOT_AUTHENTICATED"))return show("setup");setError(e.message||"לא ניתן לקרוא את Spotify");schedule(EMPTY)}}
setInterval(()=>{if(!state?.is_playing||seeking||!state?.item)return;localProgress=Math.min(localProgress+250,state.item.duration_ms);$("current").textContent=fmt(localProgress);const r=localProgress/Math.max(1,state.item.duration_ms);$("progress").value=Math.round(r*1000);tone(r,true);if(localProgress>=state.item.duration_ms){state.is_playing=false;schedule(900)}},250);
function command(fn,optimistic=null,refresh=1200){queue=queue.then(async()=>{if(Date.now()<rateLimitedUntil)return updateRate();try{setError("");if(optimistic!==null){if(state)state.is_playing=optimistic;setPlaying(optimistic)}await fn();schedule(refresh)}catch(e){const s=rate(e);if(s)enterRate(s);else{setError(e.message||"הפקודה נכשלה");schedule(2500)}}});return queue}
async function devices(){try{const d=(await window.deez.getDevices())?.devices||[];$("deviceSelect").innerHTML="";d.forEach(v=>{const o=document.createElement("option");o.value=v.id;o.textContent=`${v.name}${v.is_active?" — פעיל":""}`;o.selected=v.is_active;$("deviceSelect").appendChild(o)});if(!d.length)$("deviceSelect").innerHTML='<option value="">פתח Spotify במחשב</option>'}catch(e){const s=rate(e);s?enterRate(s):setError(e.message)}}
window.addEventListener("DOMContentLoaded",async()=>{settings=await window.deez.getSettings();applySettings();const cfg=await window.deez.getConfig();$("clientId").value=cfg.clientId||"";$("redirectUri").textContent=cfg.redirectUri;const cool=await window.deez.getRateLimit();if(cool.seconds>0)enterRate(cool.seconds);if(cfg.authenticated){show("player");if(!cool.seconds)poll()}else show("setup");
$("connectBtn").onclick=async()=>{try{$("setupStatus").textContent="פותח את Spotify…";await window.deez.startAuth($("clientId").value)}catch(e){$("setupStatus").textContent=e.message}};window.deez.onAuthComplete(()=>{show("player");poll()});window.deez.onAuthError(m=>$("setupStatus").textContent=m);
$("playBtn").onclick=()=>command(state?.is_playing?window.deez.pause:window.deez.play,!state?.is_playing);$("prevBtn").onclick=()=>command(window.deez.previous,state?.is_playing??null,1500);$("nextBtn").onclick=()=>command(window.deez.next,state?.is_playing??null,1500);
$("shuffleBtn").onclick=()=>command(()=>window.deez.shuffle(!state?.shuffle_state),null,1000);$("repeatBtn").onclick=()=>{const next=state?.repeat_state==="off"?"context":state?.repeat_state==="context"?"track":"off";command(()=>window.deez.repeat(next),null,1000)};$("likeBtn").onclick=()=>{if(!state?.item?.id)return;const next=!liked;liked=next;$("likeBtn").textContent=next?"♥":"♡";$("likeBtn").classList.toggle("on",next);command(()=>window.deez.setSaved(state.item.id,next),null,0)};
$("progress").onpointerdown=()=>seeking=true;$("progress").oninput=()=>{if(!state?.item)return;localProgress=Number($("progress").value)/1000*state.item.duration_ms;$("current").textContent=fmt(localProgress)};$("progress").onchange=async()=>{await command(()=>window.deez.seek(localProgress),null,1000);seeking=false};let vt;$("volume").oninput=()=>{$("volumeValue").textContent=`${$("volume").value}%`;clearTimeout(vt);vt=setTimeout(()=>command(()=>window.deez.volume(Number($("volume").value)),null,1200),450)};
$("refreshDevicesBtn").onclick=devices;$("useDeviceBtn").onclick=()=>{const id=$("deviceSelect").value;if(id)command(()=>window.deez.transfer(id,true),true,1800)};$("disconnectBtn").onclick=async()=>{await window.deez.logout();show("setup")};$("minBtn").onclick=window.deez.minimize;$("closeBtn").onclick=window.deez.close;$("pinBtn").onclick=async()=>{settings.pinned=!settings.pinned;await window.deez.pin(settings.pinned);$("pinBtn").style.opacity=settings.pinned?1:.55};$("miniBtn").onclick=async()=>{settings.mini=!settings.mini;applySettings();await window.deez.mini(settings.mini);await window.deez.setSettings(settings)};
$("settingsBtn").onclick=()=>$("settingsPanel").classList.remove("hidden");$("closeSettingsBtn").onclick=()=>$("settingsPanel").classList.add("hidden");$("rotationSpeed").oninput=saveSettings;$("glowToggle").onchange=saveSettings;$("compactToggle").onchange=saveSettings;$("startupToggle").onchange=async()=>{settings.startup=await window.deez.setStartup($("startupToggle").checked);$("startupToggle").checked=settings.startup};$("openLogsBtn").onclick=window.deez.openLogs;$("clearLogsBtn").onclick=async()=>{await window.deez.clearLogs();setError("הלוג נוקה")};});